version: '3'

services:
  airflow:
    image: apache/airflow:2.9.1

    container_name: airflow-local

    ports:
      - "8080:8080"

    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - .:/opt/airflow/project

    command: standalone
